#!/bin/bash


if [ $# -eq 0 ];
then
	echo "Aucun paramètre sur la ligne de commande";
else
	echo "Il y a $# paramètres sur la ligne de commande";
	echo "La liste des paramètres sont:"

	for var in $*;
	do
		echo "$var";
	done 
fi
